In [ ]:
import pandas as pd

df = pd.read_csv('dpwh_flood_control_projects.csv')

print("Shape:", df.shape)
print("\nColumn Data Types:")
print(df.dtypes)

Shape: (9855, 22)

Column Data Types:
MainIsland                     object
Region                         object
Province                       object
LegislativeDistrict            object
Municipality                   object
DistrictEngineeringOffice      object
ProjectId                      object
ProjectName                    object
TypeOfWork                     object
FundingYear                     int64
ContractId                     object
ApprovedBudgetForContract      object
ContractCost                   object
ActualCompletionDate           object
Contractor                     object
ContractorCount                 int64
StartDate                      object
ProjectLatitude               float64
ProjectLongitude              float64
ProvincialCapital              object
ProvincialCapitalLatitude     float64
ProvincialCapitalLongitude    float64
dtype: object

In [ ]:
# Check for nulls
print("Null values per column:")
print(df.isnull().sum())

Null values per column:
MainIsland                      0
Region                          0
Province                        0
LegislativeDistrict             0
Municipality                  666
DistrictEngineeringOffice       0
ProjectId                       0
ProjectName                     0
TypeOfWork                      0
FundingYear                     0
ContractId                      0
ApprovedBudgetForContract       0
ContractCost                    0
ActualCompletionDate            0
Contractor                      0
ContractorCount                 0
StartDate                       0
ProjectLatitude                 0
ProjectLongitude                0
ProvincialCapital               0
ProvincialCapitalLatitude       0
ProvincialCapitalLongitude      0
dtype: int64

In [ ]:
# Preview the data
df.head(10)

,MainIsland,Region,Province,LegislativeDistrict,Municipality,DistrictEngineeringOffice,ProjectId,ProjectName,TypeOfWork,FundingYear,...,ContractCost,ActualCompletionDate,Contractor,ContractorCount,StartDate,ProjectLatitude,ProjectLongitude,ProvincialCapital,ProvincialCapitalLatitude,ProvincialCapitalLongitude
0,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00526268LZ,Construction of Poblacion Flood Control Struct...,Construction of Flood Mitigation Structure,2021,...,92692943.8,2022-10-03,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-03-18,18.250910,121.047570,Kabugao,18.0215,121.1716
1,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00526368LZ,Construction of Cabicungan Flood Control Struc...,Construction of Flood Mitigation Structure,2021,...,47521251.3,2022-11-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.511800,121.078290,Kabugao,18.0215,121.1716
2,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00526369LZ,Construction of Sipa-San Mariano Flood Control...,Construction of Flood Mitigation Structure,2021,...,45942583.67,2022-11-28,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.270230,121.420220,Kabugao,18.0215,121.1716
3,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00561270LZ,Construction of Sta. Filomena Floodway/ Flood ...,Construction of Flood Mitigation Structure,2021,...,9900000,2022-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.535660,121.080200,Kabugao,18.0215,121.1716
4,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00561652LZ,"Construction of Sinigpit Flood Control, Calana...",Construction of Flood Mitigation Structure,2021,...,4950000,2022-09-23,ALEPHNORTH PEAK CONSTRUCTION AND DEVELOPMENT CO.,1,2021-12-01,18.527230,121.096812,Kabugao,18.0215,121.1716
5,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 1st District Engineering Office,P00526367LZ,Construction of Nabuangan River (Upstream) Flo...,Construction of Flood Mitigation Structure,2021,...,38292917.46,2022-09-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-02,17.800000,121.315833,Kabugao,18.0215,121.1716
6,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 1st District Engineering Office,P00526270LZ,Construction of Nabuangan (Upstream) Flood Con...,Construction of Flood Mitigation Structure,2021,...,80309010.27,2023-04-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-22,17.800278,121.308889,Kabugao,18.0215,121.1716
7,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620988LZ,Construction of Barren River (Upstream) Flood ...,Construction of Flood Mitigation Structure,2022,...,22928490.31,2022-11-02,PRIME MASTER CONST. AND DEV'T. CORP.,1,2022-02-09,17.823889,121.267778,Kabugao,18.0215,121.1716
8,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620472LZ,Construction of Barren River (Upstream) Flood ...,Construction of Flood Mitigation Structure,2022,...,15680000,2022-12-22,BAHRAMLEY CONSTRUCTION,1,2022-03-01,17.823889,121.267778,Kabugao,18.0215,121.1716
9,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620136LZ,Construction of Barren River (Downstream) Floo...,Construction of Flood Mitigation Structure,2022,...,51762600,2023-05-30,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-04-04,17.818333,121.268611,Kabugao,18.0215,121.1716

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/dpwh_flood_control_projects.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/dpwh_flood_control_projects.csv'

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/dpwh_flood_control_projects_copy.csv')
print("Shape:", df.shape)
print("\nColumn Data Types:")
print(df.dtypes)

Shape: (9855, 22)

Column Data Types:
MainIsland                     object
Region                         object
Province                       object
LegislativeDistrict            object
Municipality                   object
DistrictEngineeringOffice      object
ProjectId                      object
ProjectName                    object
TypeOfWork                     object
FundingYear                     int64
ContractId                     object
ApprovedBudgetForContract      object
ContractCost                   object
ActualCompletionDate           object
Contractor                     object
ContractorCount                 int64
StartDate                      object
ProjectLatitude               float64
ProjectLongitude              float64
ProvincialCapital              object
ProvincialCapitalLatitude     float64
ProvincialCapitalLongitude    float64
dtype: object

In [ ]:
print("Null values per column:")
print(df.isnull().sum())

Null values per column:
MainIsland                      0
Region                          0
Province                        0
LegislativeDistrict             0
Municipality                  666
DistrictEngineeringOffice       0
ProjectId                       0
ProjectName                     0
TypeOfWork                      0
FundingYear                     0
ContractId                      0
ApprovedBudgetForContract       0
ContractCost                    0
ActualCompletionDate            0
Contractor                      0
ContractorCount                 0
StartDate                       0
ProjectLatitude                 0
ProjectLongitude                0
ProvincialCapital               0
ProvincialCapitalLatitude       0
ProvincialCapitalLongitude      0
dtype: int64

In [ ]:
df.head(10)

,MainIsland,Region,Province,LegislativeDistrict,Municipality,DistrictEngineeringOffice,ProjectId,ProjectName,TypeOfWork,FundingYear,...,ContractCost,ActualCompletionDate,Contractor,ContractorCount,StartDate,ProjectLatitude,ProjectLongitude,ProvincialCapital,ProvincialCapitalLatitude,ProvincialCapitalLongitude
0,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00526268LZ,Construction of Poblacion Flood Control Struct...,Construction of Flood Mitigation Structure,2021,...,92692943.8,2022-10-03,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-03-18,18.250910,121.047570,Kabugao,18.0215,121.1716
1,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00526368LZ,Construction of Cabicungan Flood Control Struc...,Construction of Flood Mitigation Structure,2021,...,47521251.3,2022-11-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.511800,121.078290,Kabugao,18.0215,121.1716
2,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00526369LZ,Construction of Sipa-San Mariano Flood Control...,Construction of Flood Mitigation Structure,2021,...,45942583.67,2022-11-28,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.270230,121.420220,Kabugao,18.0215,121.1716
3,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00561270LZ,Construction of Sta. Filomena Floodway/ Flood ...,Construction of Flood Mitigation Structure,2021,...,9900000,2022-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.535660,121.080200,Kabugao,18.0215,121.1716
4,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 2nd District Engineering Office,P00561652LZ,"Construction of Sinigpit Flood Control, Calana...",Construction of Flood Mitigation Structure,2021,...,4950000,2022-09-23,ALEPHNORTH PEAK CONSTRUCTION AND DEVELOPMENT CO.,1,2021-12-01,18.527230,121.096812,Kabugao,18.0215,121.1716
5,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 1st District Engineering Office,P00526367LZ,Construction of Nabuangan River (Upstream) Flo...,Construction of Flood Mitigation Structure,2021,...,38292917.46,2022-09-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-02,17.800000,121.315833,Kabugao,18.0215,121.1716
6,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),NaN,Apayao 1st District Engineering Office,P00526270LZ,Construction of Nabuangan (Upstream) Flood Con...,Construction of Flood Mitigation Structure,2021,...,80309010.27,2023-04-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-22,17.800278,121.308889,Kabugao,18.0215,121.1716
7,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620988LZ,Construction of Barren River (Upstream) Flood ...,Construction of Flood Mitigation Structure,2022,...,22928490.31,2022-11-02,PRIME MASTER CONST. AND DEV'T. CORP.,1,2022-02-09,17.823889,121.267778,Kabugao,18.0215,121.1716
8,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620472LZ,Construction of Barren River (Upstream) Flood ...,Construction of Flood Mitigation Structure,2022,...,15680000,2022-12-22,BAHRAMLEY CONSTRUCTION,1,2022-03-01,17.823889,121.267778,Kabugao,18.0215,121.1716
9,Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620136LZ,Construction of Barren River (Downstream) Floo...,Construction of Flood Mitigation Structure,2022,...,51762600,2023-05-30,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-04-04,17.818333,121.268611,Kabugao,18.0215,121.1716

In [ ]:
print(df['ApprovedBudgetForContract'].head(10))
print("---")
print(df['ContractCost'].head(10))

0       96500000
1       49000000
2       47423180
3        9900000
4        4950000
5    39199819.73
6       82914680
7    23519997.48
8    15678924.68
9    51761907.66
Name: ApprovedBudgetForContract, dtype: object
---
0     92692943.8
1     47521251.3
2    45942583.67
3        9900000
4        4950000
5    38292917.46
6    80309010.27
7    22928490.31
8       15680000
9       51762600
Name: ContractCost, dtype: object

In [ ]:
df['ApprovedBudgetForContract'] = pd.to_numeric(df['ApprovedBudgetForContract'])
df['ContractCost'] = pd.to_numeric(df['ContractCost'])

print(df['ApprovedBudgetForContract'].dtype)
print(df['ContractCost'].dtype)

float64
float64

In [ ]:
df['ActualCompletionDate'] = pd.to_datetime(df['ActualCompletionDate'])
df['StartDate'] = pd.to_datetime(df['StartDate'])

print(df['ActualCompletionDate'].dtype)
print(df['StartDate'].dtype)

datetime64[ns]
datetime64[ns]

In [ ]:
df['Municipality'] = df['Municipality'].fillna('Unknown')

print(df['Municipality'].isnull().sum())

0

In [ ]:
df['CostVariance'] = df['ContractCost'] - df['ApprovedBudgetForContract']

df['CostVariancePct'] = (df['CostVariance'] / df['ApprovedBudgetForContract']) * 100

df['ProjectDurationDays'] = (df['ActualCompletionDate'] - df['StartDate']).dt.days

print(df[['ApprovedBudgetForContract', 'ContractCost','CostVariance', 'CostVariancePct', 'ProjectDurationDays']].head(10))

   ApprovedBudgetForContract  ContractCost  CostVariance  CostVariancePct  \
0                96500000.00   92692943.80   -3807056.20        -3.945136
1                49000000.00   47521251.30   -1478748.70        -3.017854
2                47423180.00   45942583.67   -1480596.33        -3.122094
3                 9900000.00    9900000.00          0.00         0.000000
4                 4950000.00    4950000.00          0.00         0.000000
5                39199819.73   38292917.46    -906902.27        -2.313537
6                82914680.00   80309010.27   -2605669.73        -3.142592
7                23519997.48   22928490.31    -591507.17        -2.514912
8                15678924.68   15680000.00       1075.32         0.006858
9                51761907.66   51762600.00        692.34         0.001338

   ProjectDurationDays
0                  564
1                  358
2                  362
3                  379
4                  296
5                  296
6                  478
7                  266
8                  296
9                  421

In [ ]:
print("Total rows and columns:", df.shape)
print("\nColumn data types:")
print(df.dtypes)
print("\nRemaining nulls:")
print(df.isnull().sum())

Total rows and columns: (9855, 25)

Column data types:
MainIsland                            object
Region                                object
Province                              object
LegislativeDistrict                   object
Municipality                          object
DistrictEngineeringOffice             object
ProjectId                             object
ProjectName                           object
TypeOfWork                            object
FundingYear                            int64
ContractId                            object
ApprovedBudgetForContract            float64
ContractCost                         float64
ActualCompletionDate          datetime64[ns]
Contractor                            object
ContractorCount                        int64
StartDate                     datetime64[ns]
ProjectLatitude                      float64
ProjectLongitude                     float64
ProvincialCapital                     object
ProvincialCapitalLatitude            float64
ProvincialCapitalLongitude           float64
CostVariance                         float64
CostVariancePct                      float64
ProjectDurationDays                    int64
dtype: object

Remaining nulls:
MainIsland                      0
Region                          0
Province                        0
LegislativeDistrict             0
Municipality                    0
DistrictEngineeringOffice       0
ProjectId                       0
ProjectName                     0
TypeOfWork                      0
FundingYear                     0
ContractId                      0
ApprovedBudgetForContract     157
ContractCost                   28
ActualCompletionDate            0
Contractor                      0
ContractorCount                 0
StartDate                       0
ProjectLatitude                 0
ProjectLongitude                0
ProvincialCapital               0
ProvincialCapitalLatitude       0
ProvincialCapitalLongitude      0
CostVariance                  157
CostVariancePct               157
ProjectDurationDays             0
dtype: int64

In [ ]:

problem_rows = df[df['ApprovedBudgetForContract'].isnull()]

print("Number of problem rows:", len(problem_rows))
print(problem_rows[['ProjectName', 'ApprovedBudgetForContract', 'ContractCost']].head(20))

Number of problem rows: 157
                                            ProjectName  \
81    Construction of Flood Mitigation Facilities/Dr...
84    Construction of Flood Mitigation Structure alo...
334   Construction of Mapacopaco Flood Control Struc...
335   Construction of Mapacopaco Flood Control Struc...
342   Construction of Boliwong Flood Control Structu...
363   Construction of Revetment Wall/Sheetpiling of ...
1998  Rehabilitation Flood Control Structures along ...
2124  Rehabilitation Flood Control Structures along ...
2125  Construction of Slope Protection Structure alo...
2198  Construction of Protection Works along Agno Ri...
2200  Construction of Slope Protection along Agno Ri...
2201  Construction of Slope Protection along Agno Ri...
2211  Construction of Flood Control Structure along ...
2212  Construction of Flood Control Structure along ...
2293  Construction of Flood Mitigation Structure alo...
2295  Construction of Flood Mitigation Structure alo...
4527  Construction of Riprap in Bautista Creek Banli...
4658  Construction of Detention Pond at Brgy. Mampla...
4946  Construction of Drainage, Barangay G. De Jesus...
4947  Construction of Drainage, Barangay Ramon Cruz,...

      ApprovedBudgetForContract  ContractCost
81                          NaN   49000000.00
84                          NaN   49000000.00
334                         NaN   31817660.00
335                         NaN   20914465.80
342                         NaN   36551362.81
363                         NaN           NaN
1998                        NaN    9899873.79
2124                        NaN    9899990.31
2125                        NaN   24120025.11
2198                        NaN   18983001.60
2200                        NaN    9491153.30
2201                        NaN    9491249.25
2211                        NaN    9533434.84
2212                        NaN   19066880.39
2293                        NaN           NaN
2295                        NaN           NaN
4527                        NaN    5940000.00
4658                        NaN           NaN
4946                        NaN    6929636.01
4947                        NaN    4949901.23

In [ ]:
# Reload the original file fresh
df_raw = pd.read_csv('/content/drive/MyDrive/dpwh_flood_control_projects_copy.csv')

# Look at the exact raw values in the problem rows
problem_index = [81, 84, 334, 335, 342, 363]

print(df_raw.loc[problem_index, ['ProjectName', 'ApprovedBudgetForContract']])

                                           ProjectName  \
81   Construction of Flood Mitigation Facilities/Dr...
84   Construction of Flood Mitigation Structure alo...
334  Construction of Mapacopaco Flood Control Struc...
335  Construction of Mapacopaco Flood Control Struc...
342  Construction of Boliwong Flood Control Structu...
363  Construction of Revetment Wall/Sheetpiling of ...

               ApprovedBudgetForContract
81   Clustered with Contract ID 23PD0057
84   Clustered with Contract ID 24PD0027
334  Clustered with Contract ID 22PJ0044
335  Clustered with Contract ID 22PJ0044
342  Clustered with Contract ID 22P00087
363     MYCA with Project ID P00421301LZ

In [ ]:

df_excluded = df[df['ApprovedBudgetForContract'].isnull()]

print("Excluded rows:", len(df_excluded))

Excluded rows: 157

In [ ]:
df_clean = df.dropna(subset=['ApprovedBudgetForContract', 'ContractCost']).copy()

print("Rows available for analysis:", len(df_clean))

Rows available for analysis: 9698

In [ ]:
print("Remaining nulls:")
print(df_clean.isnull().sum())
print("--")
print("Final row count:", len(df_clean))

Remaining nulls:
MainIsland                    0
Region                        0
Province                      0
LegislativeDistrict           0
Municipality                  0
DistrictEngineeringOffice     0
ProjectId                     0
ProjectName                   0
TypeOfWork                    0
FundingYear                   0
ContractId                    0
ApprovedBudgetForContract     0
ContractCost                  0
ActualCompletionDate          0
Contractor                    0
ContractorCount               0
StartDate                     0
ProjectLatitude               0
ProjectLongitude              0
ProvincialCapital             0
ProvincialCapitalLatitude     0
ProvincialCapitalLongitude    0
CostVariance                  0
CostVariancePct               0
ProjectDurationDays           0
dtype: int64
--
Final row count: 9698

In [ ]:
# Recalculate on clean data since we dropped rows
df_clean['CostVariance'] = df_clean['ContractCost'] - df_clean['ApprovedBudgetForContract']
df_clean['CostVariancePct'] = (df_clean['CostVariance'] / df_clean['ApprovedBudgetForContract']) * 100
df_clean['ProjectDurationDays'] = (df_clean['ActualCompletionDate'] - df_clean['StartDate']).dt.days

print(df_clean[['ApprovedBudgetForContract', 'ContractCost', 'CostVariance', 'CostVariancePct']].head(10))

   ApprovedBudgetForContract  ContractCost  CostVariance  CostVariancePct
0                96500000.00   92692943.80   -3807056.20        -3.945136
1                49000000.00   47521251.30   -1478748.70        -3.017854
2                47423180.00   45942583.67   -1480596.33        -3.122094
3                 9900000.00    9900000.00          0.00         0.000000
4                 4950000.00    4950000.00          0.00         0.000000
5                39199819.73   38292917.46    -906902.27        -2.313537
6                82914680.00   80309010.27   -2605669.73        -3.142592
7                23519997.48   22928490.31    -591507.17        -2.514912
8                15678924.68   15680000.00       1075.32         0.006858
9                51761907.66   51762600.00        692.34         0.001338

In [ ]:
df_clean.to_csv('/content/drive/MyDrive/dpwh_flood_control_cleaned.csv', index=False)

In [ ]:
print(df_clean[['ApprovedBudgetForContract', 'ContractCost', 'CostVariance', 'CostVariancePct']].describe())

       ApprovedBudgetForContract  ContractCost  CostVariance  CostVariancePct
count               9.698000e+03  9.698000e+03  9.698000e+03      9698.000000
mean                5.671067e+07  5.584604e+07 -8.646229e+05        -1.471839
std                 4.009798e+07  3.950550e+07  6.039573e+06         6.128792
min                 1.158000e+06  1.154359e+06 -2.364389e+08       -97.524001
25%                 2.744000e+07  2.474980e+07 -2.000023e+05        -1.006167
50%                 4.900000e+07  4.899491e+07 -2.329125e+03        -0.005019
75%                 8.685000e+07  8.656844e+07  0.000000e+00         0.000000
max                 3.105763e+08  2.895000e+08  3.747501e+06         7.721634

In [ ]:
region_counts = df_clean['Region'].value_counts()
print(region_counts)

Region
Region III                          1617
National Capital Region             1057
Region I                             843
Region IV-A                          813
Region V                             782
Region II                            626
Region VII                           614
Region VIII                          511
Region VI                            502
Region IV-B                          491
Region X                             426
Cordillera Administrative Region     347
Region XI                            344
Region XIII                          302
Region XII                           291
Region IX                            132
Name: count, dtype: int64

In [ ]:
region_variance = df_clean.groupby('Region')['CostVariancePct'].mean()
region_variance = region_variance.sort_values(ascending=False)
print(region_variance)

Region
Region VII                         -0.345283
Region XI                          -0.439379
Region XIII                        -0.473576
Region III                         -0.675919
Region II                          -0.703395
Region I                           -1.003501
Region VIII                        -1.017305
Region VI                          -1.061311
Cordillera Administrative Region   -1.220144
Region IV-A                        -1.675503
National Capital Region            -1.763755
Region XII                         -2.152429
Region X                           -2.162186
Region IV-B                        -2.497436
Region IX                          -3.262059
Region V                           -4.452332
Name: CostVariancePct, dtype: float64

In [ ]:
work_variance = df_clean.groupby('TypeOfWork')['CostVariancePct'].mean()
work_variance = work_variance.sort_values(ascending=False)
print(work_variance)

TypeOfWork
Upgrading of Drainage Structure                                0.000000
Repair/Maintenance of Flood Control Structures                -0.010158
Construction of Waterway                                      -0.147616
Construction of Spur Dike                                     -0.166356
Construction of Groundsill                                    -0.432334
Embankment                                                    -0.556578
Construction of Retarding Basin                               -0.563178
Construction of Revetment                                     -0.677892
Construction of Dike                                          -0.892556
Construction of Cutoff Channel                                -0.901460
Rehabilitation / Major Repair of Flood Mitigation Facility    -0.911886
Construction of Flood Mitigation Facility                     -1.132881
Rehabilitation / Major Repair of Slope Protection Structure   -1.325134
Construction of Slope Protection Structure                    -1.331176
Construction of Flood Mitigation Structure                    -1.500251
Rehabilitation / Major Repair of Flood Control Structure      -1.814700
Construction of Drainage Structure                            -1.982405
Rehabilitation / Major Repair of Drainage Structure           -2.313483
Name: CostVariancePct, dtype: float64

In [ ]:
yearly_variance = df_clean.groupby('FundingYear')['CostVariancePct'].mean()
yearly_variance

FundingYear
2018   -3.275939
2019   -4.493023
2020   -2.097597
2021   -3.150565
2022   -1.909448
2023   -1.263543
2024   -0.737115
2025   -1.160083
Name: CostVariancePct, dtype: float64

In [ ]:
outlier = df_clean[df_clean['CostVariancePct'] == df_clean['CostVariancePct'].min()]
print(outlier[['ProjectName', 'Region', 'ApprovedBudgetForContract', 'ContractCost', 'CostVariancePct']])

                                           ProjectName    Region  \
6556  Rehabilitation of Baybay Seawall, Malinao, Albay  Region V

      ApprovedBudgetForContract  ContractCost  CostVariancePct
6556               1.187399e+08     2940000.0       -97.524001

In [ ]:
over_budget = df_clean[df_clean['CostVariancePct'] > 0]
under_budget = df_clean[df_clean['CostVariancePct'] < 0]
exact_budget = df_clean[df_clean['CostVariancePct'] == 0]

print("Over budget:", len(over_budget))
print("Under budget:", len(under_budget))
print("Exact budget:", len(exact_budget))

Over budget: 769
Under budget: 7163
Exact budget: 1766

In [ ]:
print(df_clean.groupby('Region')['CostVariance'].mean().sort_values().head())

Region
Region V      -3.434969e+06
Region XII    -1.890411e+06
Region IX     -1.649986e+06
Region X      -1.437890e+06
Region IV-B   -1.273743e+06
Name: CostVariance, dtype: float64

In [ ]:

df_clean.to_csv('/content/drive/MyDrive/dpwh_flood_control_cleaned.csv', index=False)
print("Final clean file saved ✅")
print("Total rows:", len(df_clean))
print("Total columns:", len(df_clean.columns))

Final clean file saved ✅
Total rows: 9698
Total columns: 25